name: v0.8 Agentic Dry-Run (Advisory)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  agentic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pytest
        run: python -m pip install -U pip pytest
      - name: Run agentic test
        run: pytest -q tests/agentic/test_agentic_v08.py || true