
name: Contract Gates
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  gates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest

      - name: Golden tests (G-001..G-003, G-010)
        run: pytest -q tests/golden_cases

      - name: IR invariants (C-001..C-003)
        run: pytest -q tests/unit/test_pdf_processor_ir.py

      - name: Audit completeness + harness + exec checklist
        run: pytest -q -k "audit or run_rule or exec_checklist"
