name: Documentation Comment Bot

on:
  pull_request:
    branches: [ main ]

jobs:
  docs-comment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Run freshness check and capture output
      id: freshness-check
      run: |
        echo "Running freshness check..."
        if python scripts/check_docs_freshness.py > freshness_output.txt 2>&1; then
          echo "freshness_passed=true" >> $GITHUB_OUTPUT
        else
          echo "freshness_passed=false" >> $GITHUB_OUTPUT
        fi
        
        # Always capture the output for potential commenting
        echo "freshness_output<<EOF" >> $GITHUB_OUTPUT
        cat freshness_output.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Comment on PR if freshness check fails
      if: steps.freshness-check.outputs.freshness_passed == 'false'
      uses: actions/github-script@v6
      with:
        script: |
          const output = `${{ steps.freshness-check.outputs.freshness_output }}`;
          
          const comment = `## 📚 Documentation Synchronization Issues Found
          
          The docs freshness check detected synchronization problems that need to be addressed:
          
          \`\`\`
          ${output}
          \`\`\`
          
          ### 🔧 How to Fix
          
          **Golden Test Documentation:**
          - Ensure all golden test IDs (G-001, G-002, G-003, G-010) are referenced in:
            - \`docs/TESTING.md\`
            - \`docs/specs/pdf_processor_PRD_v0.1.md\`
            - \`Safety-Sigma-Docs/tests/golden_cases.md\`
          
          **IR Invariant Documentation:**
          - Ensure all IR invariant IDs (C-001, C-002, C-003) are referenced in:
            - \`docs/IR_SCHEMA.md\`
            - \`Safety-Sigma-Docs/ir/schema.md\`
          
          **Execution Checklist:**
          - Verify \`docs/EXEC_CHECKLIST.md\` exists and contains:
            - All validation sections (V-001 through V-005)
            - All golden test references (G-001, G-002, G-003, G-010)  
            - All IR invariant references (C-001, C-002, C-003)
            - Required file paths and at least 30 checklist items
          
          ### 📋 Use PR Template
          
          The PR template (\`.github/pull_request_template.md\`) provides a complete checklist of which documentation files to update based on your code changes.
          
          ---
          
          *This comment was generated by the docs-comment workflow. The PR will be blocked until these issues are resolved.*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
    
    - name: Comment success on PR if freshness check passes
      if: steps.freshness-check.outputs.freshness_passed == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          const comment = `## ✅ Documentation Synchronization Verified
          
          The docs freshness check passed successfully! All documentation is properly synchronized:
          
          - ✅ Golden test IDs are properly documented
          - ✅ IR invariant IDs are referenced in schema docs  
          - ✅ Execution checklist is complete and valid
          
          Great job maintaining documentation quality! 🎉
          
          ---
          
          *This comment was generated by the docs-comment workflow.*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
    
    - name: Fail workflow if freshness check failed
      if: steps.freshness-check.outputs.freshness_passed == 'false'
      run: |
        echo "❌ Documentation freshness check failed"
        echo "See PR comment for details on how to fix the issues"
        exit 1