name: Documentation Freshness Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  check-freshness:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Include Safety-Sigma-Docs submodule
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Make freshness checker executable
      run: chmod +x scripts/check_docs_freshness.py
    
    - name: Run docs freshness check
      id: freshness-check
      run: |
        echo "Running Safety Sigma docs freshness check..."
        if python scripts/check_docs_freshness.py; then
          echo "freshness_status=success" >> $GITHUB_OUTPUT
          echo "✅ Documentation is synchronized"
        else
          echo "freshness_status=failure" >> $GITHUB_OUTPUT
          echo "❌ Documentation synchronization issues found"
          exit 1
        fi
    
    - name: Report freshness results
      if: always()
      run: |
        if [ "${{ steps.freshness-check.outputs.freshness_status }}" = "success" ]; then
          echo "🎉 All documentation is fresh and synchronized!"
          echo ""
          echo "✅ Golden test IDs (G-001, G-002, G-003, G-010) are documented"
          echo "✅ IR invariant IDs (C-001, C-002, C-003) are referenced"  
          echo "✅ EXEC_CHECKLIST.md contains all validation requirements"
        else
          echo "💥 Documentation freshness check failed!"
          echo ""
          echo "This indicates one or more of:"
          echo "• Golden test IDs missing from documentation"
          echo "• IR invariant IDs not referenced in schema docs"
          echo "• EXEC_CHECKLIST.md is incomplete or missing"
          echo ""
          echo "See job output above for specific issues to fix."
        fi