name: v0.9 Memory & Reuse (Advisory)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  memory_reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install -U pip pytest
      - name: Run memory tests (advisory)
        run: |
          pytest -q tests/case_linkage/test_case_ids.py tests/memory/test_reuse_index.py tests/report/test_reuse_metrics.py || true
      - name: Test memory index building
        run: |
          PYTHONPATH=. python scripts/build_reuse_index.py || true
      - name: Test v0.9 report generation
        run: |
          PYTHONPATH=. python scripts/render_report_v09.py || true
      - name: Memory features status
        run: |
          echo "✅ Memory features tested (advisory-only, non-blocking)"
          echo "Memory tests may fail safely - they don't block core functionality"